# fly.toml file generated for foxyez-bot on 2022-12-01T20:40:02-03:00

app = "foxyez-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stdout"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"