# fly.toml app configuration file generated for foxyez-bot on 2023-05-26T16:35:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foxyez-bot"
primary_region = "scl"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
